### ISSUE TITLE
[Metrics Medel Lab]

### ISSUE THREAD

**Issue by germonprez** [oss-compass/community#10]
Thanks! Here is a link to the new Starter Project Health Metrics Model!

https://github.com/chaoss/wg-metrics-models/blob/main/metrics-model-libs/starter-project-health/definition/starter-project-health.md

# Projects to verify this model

**Comment by eyehwan** [comment]
Thank you, @germonprez. 
Our first CHAOSS MM requirement comes! That is Great! :) 
We will start the MM implementation and verification ASAP, and let you know the progress.

**Comment by lishengbao** [comment]
https://github.com/oss-compass/compass-metrics-model/pull/18

**Comment by eyehwan** [comment]
It has been deployed on compass lab.
